"""
=============================================================
  app/routes/upload.py — FastAPI Router for File Upload
=============================================================

📌 WHAT IS THIS FILE?
  The Route layer for file uploads.
  It defines the public REST API endpoint for uploading files.
  
  CLEAN ARCHITECTURE FLOW:
  1. Client sends POST request to /api/v1/upload (with file + report_id)
  2. FastAPI parses the multipart/form-data request
  3. FastAPI injects the DB session and validates parameters
  4. The request is passed to UploadController.upload_file()
  5. The Controller delegates to UploadService.process_upload()
  6. The response is returned and serialized to JSON

📌 WHAT IS MULTIPART/FORM-DATA?
  Unlike typical endpoints that accept JSON (application/json),
  file upload endpoints must accept "multipart/form-data".
  This encoding allows sending binary files alongside text fields
  (like report_id) in a single request.
"""

# ──────────────────────────────────────────────
# IMPORTS
# ──────────────────────────────────────────────

from fastapi import APIRouter, Depends, File, UploadFile, Form, status
from sqlalchemy.orm import Session
from pydantic import BaseModel, Field

# Database connection dependency
from app.database.connection import get_db

# Controller orchestration layer
from app.controllers.upload_controller import upload_controller


# ──────────────────────────────────────────────
# CREATE ROUTER
# ──────────────────────────────────────────────
router = APIRouter()


# ──────────────────────────────────────────────
# RESPONSE SCHEMA
# ──────────────────────────────────────────────

class UploadSuccessResponse(BaseModel):
    """
    Pydantic schema representing the success response for file uploads.
    FastAPI uses this to serialize the response and generate documentation.
    """
    success: bool = Field(True, description="Indicates if the upload was successful")
    message: str = Field(..., description="Details about the upload result")
    file_name: str = Field(..., description="The unique filename generated by the server")
    original_name: str = Field(..., description="The original filename uploaded by the user")
    file_path: str = Field(..., description="The local path where the file is stored")
    file_size_bytes: int = Field(..., description="The file size in bytes")
    file_type: str = Field(..., description="The file extension (pdf, png, jpg, jpeg)")
    report_id: int = Field(..., description="The ID of the report this file is linked to")


# ──────────────────────────────────────────────
# ENDPOINT: Upload File (POST /upload)
# ──────────────────────────────────────────────

@router.post(
    "/upload",
    response_model=UploadSuccessResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Upload a medical report (PDF or Image)",
    description=(
        "Accepts a PDF or image file (JPG, PNG) via multipart/form-data, "
        "validates its size and type, saves it locally on the server, "
        "and associates the saved path with the corresponding Report record in the database."
    ),
)
def upload_file(
    report_id: int = Form(
        ..., 
        description="The database ID of the report this file belongs to"
    ),
    file: UploadFile = File(
        ..., 
        description="The PDF, JPG, or PNG file to upload (maximum size 10MB)"
    ),
    db: Session = Depends(get_db)
):
    """
    Endpoint to upload a file and associate it with a medical report.

    📌 HOW FASTAPI PROCESSES THIS:
    1. **`Form(...)`**: Specifies that `report_id` is sent as a form field.
       Because multipart requests contain binary data, standard JSON bodies 
       cannot be mixed with files. Therefore, non-file parameters must be
       sent as form fields.
    2. **`File(...)`**: Tells FastAPI that `file` is an uploaded file.
       FastAPI automatically parses the file stream and provides it as
       an `UploadFile` object.
    3. **`Depends(get_db)`**: Injects a scoped database session.
    """
    # Delegate the request to the controller layer
    return upload_controller.upload_file(db=db, report_id=report_id, file=file)
